#  █████▒▄▄▄       ██▓     ██▓     ▄▄▄▄    ▄▄▄       ▄████▄   ██ ▄█▀     ██████ ▓█████  ██▀███   ██▒   █▓▓█████  ██▀███
#▓██   ▒▒████▄    ▓██▒    ▓██▒    ▓█████▄ ▒████▄    ▒██▀ ▀█   ██▄█▒    ▒██    ▒ ▓█   ▀ ▓██ ▒ ██▒▓██░   █▒▓█   ▀ ▓██ ▒ ██▒
#▒████ ░▒██  ▀█▄  ▒██░    ▒██░    ▒██▒ ▄██▒██  ▀█▄  ▒▓█    ▄ ▓███▄░    ░ ▓██▄   ▒███   ▓██ ░▄█ ▒ ▓██  █▒░▒███   ▓██ ░▄█ ▒
#░▓█▒  ░░██▄▄▄▄██ ▒██░    ▒██░    ▒██░█▀  ░██▄▄▄▄██ ▒▓▓▄ ▄██▒▓██ █▄      ▒   ██▒▒▓█  ▄ ▒██▀▀█▄    ▒██ █░░▒▓█  ▄ ▒██▀▀█▄
#░▒█░    ▓█   ▓██▒░██████▒░██████▒░▓█  ▀█▓ ▓█   ▓██▒▒ ▓███▀ ░▒██▒ █▄   ▒██████▒▒░▒████▒░██▓ ▒██▒   ▒▀█░  ░▒████▒░██▓ ▒██▒
# ▒ ░    ▒▒   ▓▒█░░ ▒░▓  ░░ ▒░▓  ░░▒▓███▀▒ ▒▒   ▓▒█░░ ░▒ ▒  ░▒ ▒▒ ▓▒   ▒ ▒▓▒ ▒ ░░░ ▒░ ░░ ▒▓ ░▒▓░   ░ ▐░  ░░ ▒░ ░░ ▒▓ ░▒▓░
# ░       ▒   ▒▒ ░░ ░ ▒  ░░ ░ ▒  ░▒░▒   ░   ▒   ▒▒ ░  ░  ▒   ░ ░▒ ▒░   ░ ░▒  ░ ░ ░ ░  ░  ░▒ ░ ▒░   ░ ░░   ░ ░  ░  ░▒ ░ ▒░
# ░ ░     ░   ▒     ░ ░     ░ ░    ░    ░   ░   ▒   ░        ░ ░░ ░    ░  ░  ░     ░     ░░   ░      ░░     ░     ░░   ░
#             ░  ░    ░  ░    ░  ░ ░            ░  ░░ ░      ░  ░            ░     ░  ░   ░           ░     ░  ░   ░
#                                       ░           ░                                                ░
# Made by CandiesJar | Github: github.com/sasi2006166 | Discord: https://discord.gg/dJ8DG2cSzt | Telegram: @CandiesJar
# Velocity configuration file

# IMPORTANT WARNING: Before reporting any issue on discord, READ carefully the comments!
# Some features are DISABLED since they're under development, don't report any bugs on them.
# Thanks for understanding.

settings:

  # Debug mode, useful for bug reports.
  # IMPORTANT: This (may) spam your console with useless messages, use it only if you're reporting a bug.
  # DISABLED.
  debug: false

  # Player with admin permission only will be able to use /fs tab complete.
  command_tab_complete: true

  # RECONNECT: Player will not be disconnected from the server, instead gets a title
  # that says "Reconnecting" with animated dots, if crashed server doesn't go again
  # online the plugin will automatically balance them tough lobbies.
  # DEFAULT: Normal kick method, after a server crash the plugin will automatically
  # balance all your kicked players.
  # IMPORTANT: This option requires a proxy reboot.
  fallback_mode: DEFAULT

  # If you want to use the reconnect mode, fallback_mode must be set to RECONNECT.
  # Those values will clear the chat on reconnect (after success) or when players
  # get fallback-ed to another server.
  clear_chat:
    fallback: true
    reconnect: false
    reconnect_join: true

  # Add here fallback lobbies, also used for /hub command.
  fallback_list:
    - lobby1
    - lobby2
    - lobby3

  # Reconnect section, it will ONLY work if fallback_mode is set to RECONNECT.
  # Customize things like delays and title mode, everything in seconds.
  auto_reconnect:
    # Tries before disconnecting or moving player to lobbies.
    max_tries: 5

    # Time before pinging the server during reconnect phase.
    # Don't put values under 1, they will NOT work.
    # In seconds.
    ping_delay: 7

    # This option is used by the addon ping system
    # for checking if the spigot instance is fully started up.
    # WARNING: Recommended to not touch.
    player_count_check: -1

    # Time for time-outing the server on ping.
    # In Milliseconds, 2000 for example = 2 seconds.
    ping_timeout: 2000

    # This option will trigger normal FallbackServer kicking procedure.
    # Sorting players in various lobbies.
    player_sort: true

    # Time before starting the server pinging on reconnect.
    # Don't put values under 1, they will NOT work.
    # In seconds.
    first_delay: 3

    # Choose if you want to clear the tab-list when
    # a player enters the "limbo" while reconnecting.
    # Useful for preventing visual bugs with names.
    clear_tab-list: true

    # Ignored reasons for reconnecting.
    # If players gets kicked for one of those reasons
    # they will not be reconnected.
    ignored_reasons:
      - "ban"
      - "kick"
      - "afk"
      - "whitelist"
      - "spam"
      - "maintenance"

    # Ignored servers for reconnecting.
    # If players gets kicked from one of those servers
    # they will not be reconnected, instead they will be
    # moved to a fallback lobby.
    # Add event servers, such as mini-games, here.
    ignored_servers:
      - lobby1
      - lobby2
      - lobby3
      - bw1
      - bw2
      - bw3

    # Option to choose if making the player join a limbo server
    # while reconnecting.
    # True: Player will be moved to limbo while reconnecting.
    # False: Player stay on kicked server while reconnecting.
    join_limbo: false

    # Title can be customized into messages configuration.
    # Available in messages.yml
    title:
      enable: true
      # NORMAL: The normal animated title with dots
      # PULSE: A title that simulates the heartbeat
      # STATIC: Title will not animate dots
      # You can customize it in messages.yml
      mode: NORMAL # DISABLED.

  # True: Normal players will not be able to see the /fs output.
  # False: Everyone will be able to see the simple "running fallbackserver" message.
  hide_command: false

  # Choose if you want to enable the updater.
  updater: true

  # In seconds, will check your lobbies every X seconds, defined under here.
  # On first start / reboot, let the plugin settle down for X seconds (defined under here) before start using fallback.
  # Recommended to use 5 if your server is in beta or have not stable spigot instances.
  ping_delay: 5

  # Checks if stats should be enabled -> https://bstats.org/plugin/bungeecord/FallbackServer/11817
  # By default this setting is set on "true" to help me improve the plugin.
  # Obviously you can disable it if you want, feel free to do so.
  telemetry: true

  # True: the plugin will automatically choose best lobby when connecting and balance all players.
  # Warning: If the list contains one lobby the balancing will not work.
  # DISABLED.
  join_balancing: false

  # Administrator will be notified which server goes down and the complete reason of shutdown.
  # DISABLED.
  admin_notification: true

  # Choose if you want to use fallbackserver's built-in command blocker.
  command_blocker: true

  # WARNING: will only work if "use_command_blocker" is set on true.
  # Add here the servers with the command(s) you want to block.
  # TEMPLATE:
  # SERVERNAME:
  #   - COMMAND1
  #   - COMMAND2
  command_blocker_list:
    hack_control:
      - lobby
      - hub
    hack_control_2:
      - lobby
      - hub

  # Disable player kicking if the plugin detects any of listed reasons.
  # Example: player gets banned on (only) spigot instance using Essentials
  # FallbackServer will disconnect him instead of kicking.
  ignored_reasons:
    - "ban"
    - "whitelist"
    - "full"

  # If you want to use the /lobby command.
  lobby_command: true

  # WARNING: works only if "lobby_command" is set on true.
  # Aliases for /lobby command, it's possible to remove the base /hub command too.
  lobby_command_aliases:
    - hub
    - lobby

  # Enable server blacklist feature, such for authentication servers.
  server_blacklist: true

  # WARNING: Works only if "server_blacklist" is set on true.
  # Add here your pre-lobbies or any server you want to disable.
  # Kicking will be disabled on those and player will be disconnected.
  server_blacklist_list:
    - prelobby1

sub_commands:

  # Enabled: true, will enable the selected sub-command.
  # Permission: permission required to use the sub-command.

  admin:
    permission: "fallback.admin"

  reload:
    permission: "fallback.admin.reload"

  debug:
    permission: "fallback.admin.debug"

  add:
    enabled: true
    permission: "fallback.admin.add"

  remove:
    enabled: true
    permission: "fallback.admin.remove"

  status:
    enabled: true
    permission: "fallback.admin.status"

  servers:
    enabled: true
    permission: "fallback.admin.servers"