#   ______ _____            _     _
# |  ____/ ____|  /\      | |   | |
# | |__ | (___   /  \   __| | __| | ___  _ __
# |  __| \___ \ / /\ \ / _` |/ _` |/ _ \| '_ \
# | |    ____) / ____ \ (_| | (_| | (_) | | | |
# |_|   |_____/_/    \_\__,_|\__,_|\___/|_| |_|
#
# Made by CandiesJar | Github: github.com/sasi2006166 | Discord: https://discord.gg/dJ8DG2cSzt | Telegram: @CandiesJar

name: FallbackServerAddon
author: CandiesJar
version: '${project.version}'
folia-supported: true
api-version: 1.13
main: me.candiesjar.fallbackserveraddon.FallbackServerAddon

softdepend:
  - PlaceholderAPI
  - ProtocolLib

commands:
    fallbackserveraddon:
        description: FallbackServerAddon's main command.
        usage: /<command> [reload]
        aliases:
          - fsa
          - fs
          - fsaddon